
import './globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MovieBook App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head><link rel="icon" href="/fav/favicon.ico" /></head>
      <body className={inter.className}>
        <Toaster/>
        {children}

        </body>
    </html>
  )
}
